### ISSUE TITLE
Kodi freezes, when opening add-on information pane

### ISSUE THREAD

**Issue by agsmf** [emilsvennesson/script.module.inputstreamhelper#156]
I have to reopen this issue again. After installing the new version 0.4.2 manually, Kodi still freezes, when opening the add-on information pane.
Tested on:
Coreelec with Kodi 18.3 on arm (Odroid C2)
Libreelec with Kodi 18.3 on x86 (Intel J3455)

**Comment by DJMix-I-Can** [comment]
I was looking into this because someone asked about it on reddit.  I have a fresh installation on Win 7 64bit laptop & Kodi 18.3 64bit. On the 0.3.5 version, it doesn't show under the Program addons.  You would need to go into the addon dependencies in order to find it. When you right click or hit C for context on InputStream Helper, select information, Kodi freezes. On the 0.4.1 version, InputStream Helper shows up under Program Addons. Right click or hit C for context on inputstream helper, select information, Kodi freezes again. I have to kill Kodi.
This is the debug file on a fresh installation, installed via zip file, no video, music, skin or program addons installed.  https://pastebin.com/Aeec4t4h

**Comment by h2lsoft** [comment]
confirmed on raspi 3+ et kodi 18

**Comment by dagwieers** [comment]
This is fixed in the v0.4.2 release that was released today. Please update your repository and/or update the add-on.

**Comment by dagwieers** [comment]
Duplicate of #147

**Comment by agsmf** [comment]
As i wrote in my first comment, i have installed **v0.4.2** manually and Kodi still freezes. What i actually recognized is, that if i use the contextmenu in the addon list and choose settings first i can get the Inputstream Helper Information without freezing Kodi. But if i choose information in the addon list ( directly or over contextmenu) Kodi freezes.

**Comment by h2lsoft** [comment]
I have installed v0.4.2 manually and Kodi still freezes exactlyy as agsmf wrote

**Comment by h2lsoft** [comment]
https://paste.kodi.tv/depajabite

**Comment by dagwieers** [comment]
The problem is that you installed it *manually*. This means Kodi is not getting new add-on information from the repository and that is why it fails. If you (re)install it from the repository, then it will work.

**Comment by dagwieers** [comment]
It is a bug in Kodi that we cannot fix. Kodi does not take use the add-on package metadata from the package in this case, and relies on metadata information that it retrieved from the repository (for v0.4.1).

**Comment by h2lsoft** [comment]
How can I uninstall it from command line ?

**Comment by dagwieers** [comment]
You could try to install **inputstreamhelper v0.4.0** and hope it will update to v0.4.2 automatically.
But I think if you install an add-on manually, the auto-update switch is off, so it won't update from a repository. And you cannot enable the auto-update switch from the GUI, because it will still fail to open.

Normally I would say, remove it and reinstall it from the repository, but you cannot because it is required by other add-ons, so removal is not possible. It's a catch-22.

My solution when debugging this was to open the Addons database using sqlite and remove the addon entry manually, then reinstall v0.4.0 from ZIP, and then enable auto-update switch. See https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/147#issuecomment-527492196

**Comment by dagwieers** [comment]
Not sure if https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/156#issuecomment-528041546 is true, but if you can get into the information pane like that, you can simply reinstall v0.4.2 from the repository *and* enable auto-update. I doubt this is possible, but if it works, that's the easiest way out.

**Comment by dagwieers** [comment]
Maybe reinstalling v0.4.2 again may do the trick as well, since it may get the (now available) v0.4.2 metadata from the repository instead. But you may have to first downgrade to e.g. v0.4.0 and then upgrade again to v0.4.2.

**Comment by agsmf** [comment]
For me it worked this way. Thanks!

**Comment by h2lsoft** [comment]
Now, its is ok, downgrade to 0.4.0 and update to 0.4.2.

Thanks

**Comment by dagwieers** [comment]
@agsmf @h2lsoft Do not forget to enable auto-update again in the information pane.

If you have thoughts of how to improve InputStream Helper, we would like to hear as well :wink:

**Comment by h2lsoft** [comment]
done ! no problem ;-)

**Comment by dagwieers** [comment]
I pinned this issue at the top of the issues list, as more people might be affected by this. I also opened a new issue to track reporting this upstream.
